### ISSUE TITLE
getDxy.pl comment

### ISSUE THREAD

**Issue by glagunas** [mfumagalli/ngsPopGen#8]
If I am not mistaken, according to the file input from maf,

`if(($parts[6]>=$minInd)&&($parts2[6]>=$minInd))
`
should read

`if(($parts[7]>=$minInd)&&($parts2[7]>=$minInd))`

since nInd is column 8,

**Comment by glagunas** [comment]
The input format asks for a ref column but I think that the ref column is not being taken into account. Dxy is being calculated based on the ref column if it is present at part[4]

**Comment by mfumagalli** [comment]
thank you for spotting this; I can't remember who wrote this script. It depends on which option you choose in ANGSD to calculate allele frequencies (-doMaf). I suspect this script assumes you use -doMaf 3 which is a bit unusual. I would change the script assuming you use -doMaf 1 so you have only one column for the allele frequencies (knownEM) and the last one will always be the nr of individuals. Are you able to do that? If so, can you pull a request? Thanks, otherwise please let me know.

**Comment by mfumagalli** [comment]
yes, please suggest the specific changes

**Comment by mfumagalli** [comment]
fixed
